### ISSUE TITLE
流程变量没有生效

### ISSUE THREAD

**Issue by jfld** [young-datafan-ooooo1/data-integration#100]
![微信图片_20220622153020](https://user-images.githubusercontent.com/21107515/174970295-e528e75c-f1ae-4c61-bde0-37c865e6ca1d.png)
![微信图片_20220622153028](https://user-images.githubusercontent.com/21107515/174970327-a307f61b-6828-432c-802a-2513410a6dc4.png)
![微信图片_20220622153033](https://user-images.githubusercontent.com/21107515/174970458-cf3de736-bf93-4159-a821-a6d47e43dc73.png)

**Comment by EchoXiaoLang** [comment]
@jfld 感谢提出，这个会在下一个版本的中修复
