### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by Mzdream** [young-datafan-ooooo1/data-integration#103]
登录报错 “系统繁忙” 不知道是什么意思

**Comment by EchoXiaoLang** [comment]
@FreedBird  你贴出system-manage 服务和sso服务的日志

**Comment by Mzdream** [comment]
![1658139890469](https://user-images.githubusercontent.com/39087939/179492636-8d686170-c357-4adb-a3f0-4e367bb34b42.jpg)
上面这个图片是网关报错截图，
其他的服务我看没有任何报错

**Comment by EchoXiaoLang** [comment]
@FreedBird  java.net.UnknownHostException 这个需要你改下windows host 文件

**Comment by Mzdream** [comment]
哦哦  你是说在host文件中配置映射是吗？如果是我要怎么配置，把谁映射成谁呢？
