### ISSUE TITLE
前端在本机部署后无样式

### ISSUE THREAD

**Issue by virtuouser** [young-datafan-ooooo1/data-integration#104]
按步骤来，在本机上部署，可以运行，但是这样式不知道什么问题显示不出来，查了好久还是弄不出来
![image](https://user-images.githubusercontent.com/55575215/178698858-5d3c7e08-c920-4099-ae20-b2827acf8b58.png)
![image](https://user-images.githubusercontent.com/55575215/178699164-505f9a5c-131c-4c13-992f-a4edaf8022d2.png)

**Comment by virtuouser** [comment]
已解决，我是复制readme里的路径 http://127.0.0.1:8081/dataintegration-ui/#/ 启动的，这个可以访问但是没样式，
改为 http://127.0.0.1:8081/dataintegration-ui 访问就有样式了，
![image](https://user-images.githubusercontent.com/55575215/178704893-1667e16f-474d-4a91-854a-094eafa17f0b.png)

![image](https://user-images.githubusercontent.com/55575215/178704779-1f55c08d-58ac-40d1-9425-b0b1995407fb.png)

结果还是路径问题，还以为我这少了步骤，有点小尴尬

**Comment by TellMeIt** [comment]
你是docker还是win安装的呢？安装后报错了吗？也得安consul吧
org.springframework.beans.factory.**_UnsatisfiedDependencyException_**: Error creating bean with name '_dpFileRegularCleanController_' defined in file [G:\...\controller\DpFileRegularCleanController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name '_dpFileRegularCleanServiceImpl_': Unsatisfied dependency expressed through field '_dpPortalFileManagerService'_; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '_dpPortalFileManagerServiceImpl_': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '_minIoFileSystemManagerServiceImpl_': Invocation of init method failed; nested exception is com.youngdatafan.dataintegration.core.exception.DpException: 初始化minIo配置异常
