### ISSUE TITLE
登录不了。token报错，求解决方法

### ISSUE THREAD

**Issue by cly-123** [young-datafan-ooooo1/data-integration#108]
![image](https://user-images.githubusercontent.com/112066550/193200477-e7ea9139-9611-4e41-bb99-14230d337d34.png)

![image](https://user-images.githubusercontent.com/112066550/193200592-f3023f91-408b-4340-9fdb-7ed7f2792c32.png)
将地址改为  http://127.0.0.1:10200/api/dataintegration-common-sso-provider/oauth/token  报错如下
![image](https://user-images.githubusercontent.com/112066550/193201662-f1de90f6-1b20-48ef-a44b-60eb958401dc.png)

![image](https://user-images.githubusercontent.com/112066550/193201396-dce2f8a8-4fed-40d4-a71a-be43b82cccd2.png)

**Comment by EchoXiaoLang** [comment]
你可以将geteway 的详细日志保存成文件发下

**Comment by cly-123** [comment]
> 
[geteway.pdf](https://github.com/young-datafan/data-integration/files/9682563/geteway.pdf)

**Comment by TellMeIt** [comment]
前端要改两三个地方的localhost，你可能没找全，在api里再找找
