### ISSUE TITLE
请问http请求完成查询后如何取值？没有json输出组件

### ISSUE THREAD

**Issue by Mrhuangtao** [young-datafan-ooooo1/data-integration#110]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by EchoXiaoLang** [comment]
@Mrhuangtao 目前没有json输出组件，你可以输出txt文件或者其他文件试试

**Comment by TellMeIt** [comment]
你是docker还是win安装的呢？安装后报错了吗？也得安consul吧
org.springframework.beans.factory.**_UnsatisfiedDependencyException_**: Error creating bean with name '_dpFileRegularCleanController_' defined in file [G:\...\controller\DpFileRegularCleanController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name '_dpFileRegularCleanServiceImpl_': Unsatisfied dependency expressed through field '_dpPortalFileManagerService'_; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '_dpPortalFileManagerServiceImpl_': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '_minIoFileSystemManagerServiceImpl_': Invocation of init method failed; nested exception is com.youngdatafan.dataintegration.core.exception.DpException: 初始化minIo配置异常
