### ISSUE TITLE
sql文件导入出现问题

### ISSUE THREAD

**Issue by ganyuanjiang** [young-datafan-ooooo1/data-integration#116]
[SQL] Query dataintegration start
[ERR] 2006 - MySQL server has gone away
[ERR] 
INSERT INTO `dp_portal_project_file` VALUES ('011928eb42c3449bb73677892421b26c','{\"transformation\":{\"info\":{\"name\":\"输入输出插件测试\",\"description\":\"\",\"extended_description\":\"\",\"trans_version\":\"\",\"trans_type\":\"Normal\",\"directory\":\"/home/admin\",\"parameters\":\"\",\"log\":\"\",\"maxdate\":{\"connection\":\"\",\"table\":\"\",\"field\":\"\",\"offset\":0,\"maxdiff\":0},\"size_rowset\":10000,\"sleep_time_empty\":50,\"sleep_time_full\":50,\"unique_connections\":\"N\",\"feedback_shown\":\"Y\",\"feedback_size\":50000,\"using_thread_priorities\":\"Y\",\"shared_objects_file\":\"\",\"capture_step_performance\":\"N\",\"step_performance_capturing_delay\":1000,\"step_performance_capturing_size_limit\":100,\"dependencies\":\"\",\"partitionschemas\":\"\",\"slaveservers\":\"\",\"clusterschemas\":\"\",\"created_user\":\"14bf35b8-d342-4663-9550-5466f0b454d0\",\"created_date\":\"2020/08/05 17:33:50\",\"modified_user\":\"admin\",\"modified_date\":\"2020/02/19 17:08:25.150\",\"key_for_session_key\":\"\",\"is_key_private\":\"N\"},\"notepads\":\"\",\"connection\":[{\"name\":\"d618f2e8-dd1f-4254-b9ad-776a96a1f365\",\"server\":\"\",\"type\":\"POSTGRESQL\",\"access\":\"Native\",\"database\":\"\",\"port\":0,\"username\":\"postgres\",\"password\":\"Encrypted 2be98afc86aa78296a214ab508cc2fd8a\",\"servername\":\"\",\"data_tablespace\":\"\",\"index_tablespace\":\"\",\"attributes\":{\"attribute\":[{\"code\":\"PORT_NUMBER\",\"attribute\":0},{\"code\":\"CUSTOM_DRIVER_CLASS\",\"attribute\":\"org.postgresql.Driver\"},{\"code\":\"CUSTOM_URL\",\"attribute\":\"jdbc:postgresql://192.168.124.177:5432/postgres\"}]},\"dataSourceName\":\"\",\"dsName\":\"all_type_pg\",\"dataSourceId\":\"d618f2e8-dd1f-4254-b9ad-776a96a1f365\"}],\"order\":{\"hop\":[{\"sourceUUId\":\"bcCsvInputdadfbsource\",\"targetUUId\":\"CsvFileOutput61aa9\",\"fromId\":\"bcCsvInputdadfb\",\"toId\":\"CsvFileOutput61aa9\",\"from\":\"csv文件输入\",\"to\":\"输出到csv\",\"enabled\":\"Y\"},{\"sourceUUId\":\"bcExcelInput01cd2source\",\"targetUUId\":\"ExcelFileOutput99d1d\",\"fromId\":\"bcExcelInput01cd2\",\"toId\":\"ExcelFileOutput99d1d\",\"from\":\"excel文件输入\",\"to\":\"输出到excel\",\"enabled\":\"Y\"},{\"sourceUUId\":\"bcTxtInputb645asource\",\"targetUUId\":\"bcFileOutput96741\",\"fromId\":\"bcTxtInputb645a\",\"toId\":\"bcFileOutput96741\",\"from\":\"txt文件输入\",\"to\":\"输出到文件\",\"enabled\":\"Y\"}]},\"step\":[{\"file_server_type\":\"s3\",\"showFileName\":\"data.xls\",\"filePath\":\"s3://192.168.124.166:19000/dp-s3/14bf35b8-d342-4663-9550-5466f0b454d0/0684a105ddc6489eb84dec67ee05ef88/0373b970c125436a84d42882d837ff10.xls\",\"fsuserName\":\"prime\",\"fspassWord\":\"IYrEJt2R4oMID0nRnavE2A==\",\"tableName\":\"bcExcelInput01cd2\",\"name\":\"excel文件输入\",\"fileId\":\"0373b970c125436a84d42882d837ff10\",\"stepType\":\"excel文件输入\",\"describe\":\"\",\"initFlag\":true,\"type\":\"bcExcelInput\",\"modelName\":\"\",\"description\":\"\",\"distribute\":\"Y\",\"custom_distribution\":\"Y\",\"copies\":1,\"partitioning\":{\"method\":\"none\",\"schema_name\":\"\"},\"header\":\"Y\",\"noempty\":\"Y\",\"stoponempty\":\"Y\",\"filefield\":[\"\",\"\"],\"sheetfield\":[\"\",\"\"],\"sheetrownumfield\":\"\",\"rownumfield\":\"\",\"limit\":0,\"encoding\":\"UTF-8\",\"add_to_result_filenames\":\"Y\",\"accept_filenames\":\"N\",\"accept_field\":\"\",\"accept_stepname\":\"\",\"file\":{\"name\":\"s3://192.168.124.166:19000/dp-s3/14bf35b8-d342-4663-9550-5466f0b454d0/0684a105ddc6489eb84dec67ee05ef88/0373b970c125436a84d42882d837ff10.xls\",\"filemask\":\"a\",\"exclude_filemask\":\"\",\"file_required\":\"N\",\"include_subfolders\":\"N\"},\"fields\":{\"field\":[{\"name\":\"a\",\"nameCn\":\"a\",\"type\":\"Number\",\"length\":-1,\"precision\":-1,\"trim_type\":0,\"repeat\":\"N\",\"format\":\"\",\"currency\":null,\"decimal\":\".\",\"group\":\",\"},{\"name\":\"b\",\"nameCn\":\"b\",\"type\":\"Number\",\"length\":-1,\"precision\":-1,\"trim_type\":0,\"repeat\":\"N\",\"format\":\"\",\"currency\":null,\"decimal\":\".\",\"group\":\",\"},{\"name\":\"c\",\"nameCn\":\"c\",\"type\":\"Number\",\"length\":-1,\"precision\":-1,\"trim_type\":0,\"repeat\":
[SQL] Finished with error

**Comment by toby1123yjh** [comment]
同样有这个问题
