### ISSUE TITLE
求拉交流群

### ISSUE THREAD

**Issue by 728450574** [young-datafan-ooooo1/data-integration#128]
代码运行上有bug，想进交流群学习

**Comment by 728450574** [comment]
@zhangrenhua @

**Comment by zhangrenhua** [comment]
![IMG_5064](https://user-images.githubusercontent.com/11753647/237044230-acab4c2b-9d46-4d18-94d9-34089d413084.JPG)

最近大伙都比较忙，有啥问题群里问。
