### ISSUE TITLE
求群，依赖下不下来

### ISSUE THREAD

**Issue by wujt1084** [young-datafan-ooooo1/data-integration#130]
如题，求群，依赖下不下来

**Comment by wujt1084** [comment]
![image](https://github.com/young-datafan-ooooo1/data-integration/assets/127291078/14da9a76-dafc-4bd0-802e-898c423974a4)
启动成功

**Comment by wuxiao-ling197** [comment]
@wujt1084 你好 能请教一下吗  本地部署的时候安装前端依赖报错，谷歌了一下说是webpack和sass-loader 版本对不上，但是我降版本安装sass-loader也一直安装不上，还有根目录执行mvn的时候也报错，查了好多都处理不了，可以指教一下吗？
![1](https://github.com/young-datafan-ooooo1/data-integration/assets/77096395/14f7e378-fb4a-4a50-b14f-4ae831bb1879)
![2](https://github.com/young-datafan-ooooo1/data-integration/assets/77096395/a18cb649-e5c1-41d1-8458-93619615e688)
