### ISSUE TITLE
JdbcUtil getDatabaseConnect 方法中 第24行XML.toString(new JSONLinkedObject(projectFile)) XML的包使用错误，导致在插件使用过程中无法顺利将JSON转换为XML

### ISSUE THREAD

**Issue by AzathoX** [young-datafan-ooooo1/data-integration#131]
**Describe the bug**
表输出插件模式查询中无法使用报错

**To Reproduce**
1. 数据集成工具
2. 创建项目
3. 将表输出插件拖到中间画布上
4. 目标模式无法获取
5. 导致点击运行时报错不存在目标表
![image](https://github.com/young-datafan-ooooo1/data-integration/assets/54365208/baeea244-613c-49e1-bfb5-585c8dd00577)

**Expected behavior**
可获取模式
已修复
原因是 getDatabaseConnect 方法中 第24行XML.toString(new JSONLinkedObject(projectFile)) ，导入XML的包使用错误，导致在插件使用过程中无法顺利将JSON转换为XML

**Comment by yoonching** [comment]
我个人用的一个可行的修改方式：

在com.youngdatafan.portal.model.management.util.jdbc.JdbcUtils中，将 private static Database getDatabaseConnect(DatasourceDTO datasourceDTO)方法的

`        projectFile = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
                + XML.toString(new JSONLinkedObject(projectFile));`
改为

`        projectFile = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
                + XML.toString(new JSONObject(projectFile));`

既将这里com.youngdatafan.dataintegration.core.util.json.JSONLinkedObject改为org.json.JSONObject
