### ISSUE TITLE
数据库文件

### ISSUE THREAD

**Issue by cs3163077** [young-datafan-ooooo1/data-integration#44]
没有数据库文件

**Comment by zhangrenhua** [comment]
最近还在整理文档阶段，很快就会补齐这块的内容哈。

**Comment by AiMing317** [comment]
同求一份sql文件。希望能有一些文档

**Comment by zhangrenhua** [comment]
这几天正在整理快速上手的文档哈，数据库文件会同文档一起出来，稍等两天

**Comment by AiMing317** [comment]
期待早点发布  加油大佬

**Comment by EchoXiaoLang** [comment]
sq

> 同求一份sql文件。希望能有一些文档

sql 文件在/install/sql 目录下

**Comment by EchoXiaoLang** [comment]
可以参考：https://www.young-datafan.com/docs-data-integration/quick-start/installation-docker/.          这个文档部署演示
