### ISSUE TITLE
新建数据连接存在异常

### ISSUE THREAD

**Issue by AiMing317** [young-datafan-ooooo1/data-integration#59]
新建数据连接时存在异常 数据库名称带有 **‘-’** 保存时忽略后面参数导致无法连接数据库。另外创建项目时怎么关联两个步骤？是功能缺失了么

**Comment by EchoXiaoLang** [comment]
> 新建数据连接时存在异常 数据库名称带有 **‘-’** 保存时忽略后面参数导致无法连接数据库。另外创建项目时怎么关联两个步骤？是功能缺失了么

1:我这边测mysql数据库为**‘-’**这种格式的，是可以测试连接和保存，
2:关于怎么关联两个步骤，可以通过按住shift ，然后选中控件，按住鼠标左键移动，会有一根连接线，后续会有操作文档的更新。

**Comment by virtuouser** [comment]
我是在连接 sqlserver 时出现这个错的，比如说我的数据库名称是 xxl-job，页面显示的是 xxl，保存的时候没错，是进入表输入，然后编辑数据库连接回显时错了，我看了下后端，好像是 explainURL 这个方法截取字符串出了问题
大概是这样的
![image](https://user-images.githubusercontent.com/55575215/178942384-3de0caf8-fbac-4bf4-a0ef-2158f849810f.png)
修改一下匹配正则就好了 ([\w.]+):(\d+)[:/]?([\w.-]+)?
