### ISSUE TITLE
希望能够丰富一下代码启动的说明文档

### ISSUE THREAD

**Issue by lesliechueng** [young-datafan-ooooo1/data-integration#61]
例如各个工程启动顺序，以及需要修改的配置文件，帮助想加入的人员快速掌握整个工程

**Comment by EchoXiaoLang** [comment]
> 例如各个工程启动顺序，以及需要修改的配置文件，帮助想加入的人员快速掌握整个工程

谢谢您的建议，这边正在做文档的补全，后续补充完成，会通知您的

**Comment by EchoXiaoLang** [comment]
> 例如各个工程启动顺序，以及需要修改的配置文件，帮助想加入的人员快速掌握整个工程

>本地启动可以参考 redeme 快速构建
