### ISSUE TITLE
oauth2错误, 前端项目无法登录

### ISSUE THREAD

**Issue by xiangzou** [young-datafan-ooooo1/data-integration#63]
前端项目启动后无法登录 需要访问 oauth2 获取token, 一直99999  导致卡在登录页面

**Comment by EchoXiaoLang** [comment]
> 前端项目启动后无法登录 需要访问 oauth2 获取token, 一直99999 导致卡在登录页面

我这边测试一下，处理好了，会通知你。

**Comment by xiangzou** [comment]
> > 前端项目启动后无法登录 需要访问 oauth2 获取token, 一直99999 导致卡在登录页面
> 
> 我这边测试一下，处理好了，会通知你。
项目跑不通, 有很多外部资源,  getaway转发貌似也有问题

**Comment by EchoXiaoLang** [comment]
> > > 前端项目启动后无法登录 需要访问 oauth2 获取token, 一直99999 导致卡在登录页面
> > 
> > 
> > 我这边测试一下，处理好了，会通知你。
> > 项目跑不通, 有很多外部资源,  getaway转发貌似也有问题
你可以参考这个，刚才有位用户提供gateway错误日志信息，已经帮他解决了。
https://github.com/young-datafan/data-integration/issues/64

**Comment by cly-123** [comment]
> 
你这个解决了吗，我也这样
