### ISSUE TITLE
有没有本地调试文档，本地部署配置文件修改等信息

### ISSUE THREAD

**Issue by zghfyy** [young-datafan-ooooo1/data-integration#64]

**Comment by EchoXiaoLang** [comment]
> _No description provided._

本地部署文档已经在整理，估计周末可以发布文档地址。

**Comment by zghfyy** [comment]
请问windows 部署的文档有没有？

**Comment by EchoXiaoLang** [comment]
> 请问windows 部署的文档有没有？

本地部署启动的话，是项目启动是支持windows，不过像前置环境jdk consul 、minio 、maven、 mysql需要自己参考网上部署了，我这边没有window环境，写实际操作步骤，我这边会提供mac的安装步骤。部署配置文件修改和启动步骤是通用的。

**Comment by EchoXiaoLang** [comment]
> > 请问windows 部署的文档有没有？
> 
> 本地部署启动的话，是项目启动是支持windows，不过像前置环境jdk consul 、minio 、maven、 mysql需要自己参考网上部署了，我这边没有window环境，写实际操作步骤，我这边会提供mac的安装步骤。部署配置文件修改和启动步骤是通用的。

这边会提供版本相关的信息。

**Comment by zghfyy** [comment]
你好，我前端登录也出现了99999的问题，请问这个是路由的配置问题么还是什么？需要怎么处理？

**Comment by EchoXiaoLang** [comment]
> 你好，我前端登录也出现了99999的问题，请问这个是路由的配置问题么还是什么？需要怎么处理？

![image](https://user-images.githubusercontent.com/25915539/162909651-9e2a5180-314f-40a8-a0cd-121c0ca79eed.png)
上面是我vx，或者你可以看下docker启动后的 gateway服务的日志信息，发我一份

**Comment by EchoXiaoLang** [comment]
[zghfyy](https://github.com/zghfyy)：提供gateway服务的日志信息，java.net.UnknownHostException: failed to resolve 'DESKTOP-3K6ATDQ' after 4 queries
 解决方式，修改host文件：127.0.0.1 DESKTOP-3K6ATDQ
