### ISSUE TITLE
windows 中编译遇到的问题

### ISSUE THREAD

**Issue by a19920714liou** [young-datafan-ooooo1/data-integration#66]
运行环境在windows中
1.openoffice中dockerfile copy的jdk需要放到openoffice文件夹中
2.openoffice中dockerfile 中yum install 指定了/zh-CN/，但其实没有这个路径，且openoffice4.1.11-redhat-menus-4.1.11-9808这个版本没有提交，现在是4.1.1-9775
3.脚本中没有对ui进行编译与打包
4.文档中修改ip地址哪里，没有对redis的地址和端口号进行修改

**Comment by EchoXiaoLang** [comment]
> 运行环境在windows中 1.openoffice中dockerfile copy的jdk需要放到openoffice文件夹中 2.openoffice中dockerfile 中yum install 指定了/zh-CN/，但其实没有这个路径，且openoffice4.1.11-redhat-menus-4.1.11-9808这个版本没有提交，现在是4.1.1-9775 3.脚本中没有对ui进行编译与打包 4.文档中修改ip地址哪里，没有对redis的地址和端口号进行修改

你拉取最新的代码，然后redis端口是docker compose会完成这个，redis docker会启动一个
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/25915539/162947458-724e312b-c2d3-4e6d-b33f-8dd0693fdadb.png">
