### ISSUE TITLE
在centos7中编译遇到的问题

### ISSUE THREAD

**Issue by a19920714liou** [young-datafan-ooooo1/data-integration#67]
1.docker部署文档中执行命令是sh install/install.sh 127.0.0.1，但是必须cd到install执行sh install.sh 127.0.0.1
2.mysql、redis、minio、consul因为挂载磁盘会有权限问题，我是增加了privileged: true
3.默认生成的msyql用户密码与项目中有区别，需要手动创建账号密码并授权
4.数据集成里面其他菜单里面的功能是还没实现么，点开内容都是空的

**Comment by EchoXiaoLang** [comment]
> 1.docker部署文档中执行命令是sh install/install.sh 127.0.0.1，但是必须cd到install执行sh install.sh 127.0.0.1 2.mysql、redis、minio、consul因为挂载磁盘会有权限问题，我是增加了privileged: true 3.默认生成的msyql用户密码与项目中有区别，需要手动创建账号密码并授权 4.数据集成里面其他菜单里面的功能是还没实现么，点开内容都是空的

谢谢你的建议，
目前数据集成，有项目和管理和运行菜单开放。
