### ISSUE TITLE
项目上线功能不可用

### ISSUE THREAD

**Issue by dopsieee** [young-datafan-ooooo1/data-integration#73]
**Describe the bug**
项目上线功能不可用

**To Reproduce**
1. 点击管理
2. 选择项目管理
3. 点击某个项目的“上线”操作按钮

**Expected behavior**
显示系统繁忙

**Version**
2022.04.24 从仓库中拉取的版本

请问是功能还在开发中么，谢谢

**Comment by EchoXiaoLang** [comment]
> **Describe the bug** 项目上线功能不可用
> 
> **To Reproduce**
> 
> 1. 点击管理
> 2. 选择项目管理
> 3. 点击某个项目的“上线”操作按钮
> 
> **Expected behavior** 显示系统繁忙
> 
> **Version** 2022.04.24 从仓库中拉取的版本
> 
> 请问是功能还在开发中么，谢谢

这个上线功能还在开发中，那部分服务暂时还没加入集成

**Comment by dopsieee** [comment]
好的，谢谢。
