### ISSUE TITLE
支持odbc连接方式吗

### ISSUE THREAD

**Issue by I-am-lee** [young-datafan-ooooo1/data-integration#74]
请问下 现在的1.0版本支持odbc方式连接数据库吗

**Comment by EchoXiaoLang** [comment]
> 请问下 现在的1.0版本支持odbc方式连接数据库吗

暂时不支持，您可以在dataintegration-model 和dataintegration-run pom中加入ojdbc驱动依赖，插件表输入新建数据源选择odjc方式连接。

**Comment by I-am-lee** [comment]
好的 谢谢
