### ISSUE TITLE
请问下文件服务怎么改成ftp？目前只支持s3吗

### ISSUE THREAD

**Issue by wxdx** [young-datafan-ooooo1/data-integration#75]

**Comment by EchoXiaoLang** [comment]
目前已经支持s3和minio，如果想支持ftp可以基于com.youngdatafan.dataintegration.file.management.service.FileSystemManagerService，可以提pr，参考MinIoFileSystemManagerServiceImpl或者S3FileSystemManagerServiceImpl实现

**Comment by wxdx** [comment]
@EchoXiaoLang  好的您 谢谢
