### ISSUE TITLE
请问文件minio是不是还没完全支持？

### ISSUE THREAD

**Issue by lesliechueng** [young-datafan-ooooo1/data-integration#76]
![image](https://user-images.githubusercontent.com/13750154/168282805-73124c84-f215-4c2d-8ca3-b0d3d52644d3.png)
选择minio文件报错，debug发现这里还没有minio的处理方法

**Comment by EchoXiaoLang** [comment]
这块我明天更新一下

**Comment by EchoXiaoLang** [comment]
> ![image](https://user-images.githubusercontent.com/13750154/168282805-73124c84-f215-4c2d-8ca3-b0d3d52644d3.png) 选择minio文件报错，debug发现这里还没有minio的处理方法

你更新最新的代码，重新上传文件就可以了。

**Comment by lesliechueng** [comment]
> > ![image](https://user-images.githubusercontent.com/13750154/168282805-73124c84-f215-4c2d-8ca3-b0d3d52644d3.png) 选择minio文件报错，debug发现这里还没有minio的处理方法
> 
> 你更新最新的代码，重新上传文件就可以了。

多谢，我试一下
