### ISSUE TITLE
功能新增

### ISSUE THREAD

**Issue by srqy** [young-datafan-ooooo1/data-integration#80]
后续会考虑增加JSON输入、Streaming中的JMS、MQTT生产者和消费者以及作业的功能吗，还有其它的数据治理的模者和消费者以及作业的功能吗，还有其它的数据治理的模块后续会开源吗？

**Comment by EchoXiaoLang** [comment]
> 后续会考虑增加JSON输入、Streaming中的JMS、MQTT生产者和消费者以及作业的功能吗，还有其它的数据治理的模者和消费者以及作业的功能吗，还有其它的数据治理的模块后续会开源吗？

这个后续会陆续增加的

**Comment by srqy** [comment]
预计全部功能会什么时候开源出来啊

**Comment by EchoXiaoLang** [comment]
> 预计全部功能会什么时候开源出来啊

这个不太好估计，如果可以你可以提pr，一起参与开源项目的开发，贡献自己的代码
