### ISSUE TITLE
项目管理-上线-提交上线显示系统繁忙，后台报404

### ISSUE THREAD

**Issue by henryyanhwang** [young-datafan-ooooo1/data-integration#82]
**项目管理-上线-提交上线显示系统繁忙，后台报404**

1. Go to '管理'
2. Click on '上线'
3. Scroll down to '提交上线界面'
4. 界面报“系统繁忙”，后台报not found 404 异常

报错url路径：
 http://127.0.0.1:10200/api/dp-schedule-online-audit-provider/dpPortalFrequency?frequencyName=

![image](https://user-images.githubusercontent.com/106228936/170200833-6dedad82-6828-4aaa-b06a-eaa7df02fe0f.png)

![}DIABL8~AJDU5YY%Y%CAD26](https://user-images.githubusercontent.com/106228936/170200875-651a35fa-9eb3-4138-8647-8a8f4d8d7b63.jpg)

**Comment by EchoXiaoLang** [comment]
> **项目管理-上线-提交上线显示系统繁忙，后台报404**
> 
> 1. Go to '管理'
> 2. Click on '上线'
> 3. Scroll down to '提交上线界面'
> 4. 界面报“系统繁忙”，后台报not found 404 异常
> 
> 报错url路径： http://127.0.0.1:10200/api/dp-schedule-online-audit-provider/dpPortalFrequency?frequencyName=
> 
> ![image](https://user-images.githubusercontent.com/106228936/170200833-6dedad82-6828-4aaa-b06a-eaa7df02fe0f.png)
> 
> ![}DIABL8~AJDU5YY%Y%CAD26](https://user-images.githubusercontent.com/106228936/170200875-651a35fa-9eb3-4138-8647-8a8f4d8d7b63.jpg)

这个项目上线的功能暂时没有开放，后续会开放相应的功能

**Comment by henryyanhwang** [comment]
好的，期待上线！
