### ISSUE TITLE
这个项目不是完全开放的吗，缺少服务dp-schedule-online-audit-provider

### ISSUE THREAD

**Issue by joely110** [young-datafan-ooooo1/data-integration#83]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by EchoXiaoLang** [comment]
目前开放的数据集成属于公司项目的其中的一个子模块，项目上线运行模块暂时还未开放，后续会开放
