### ISSUE TITLE
请问其他文件夹下的组件是不是都是待实现的？

### ISSUE THREAD

**Issue by lesliechueng** [young-datafan-ooooo1/data-integration#85]
如题，多谢回答

**Comment by EchoXiaoLang** [comment]
> 如题，多谢回答

其他文件夹下打开时空白的，说明就是带实现的

**Comment by lesliechueng** [comment]
> 

您能抽空写一下项目包介绍以及开发流程嘛？想有机会也能参与进来，可以以开发一个组件为例大概描述下开发流程和执行流程，这样也可以帮助其他人更快上手，授人以鱼不如授人以渔，多谢了

**Comment by EchoXiaoLang** [comment]
> > 
> 
> 您能抽空写一下项目包介绍以及开发流程嘛？想有机会也能参与进来，可以以开发一个组件为例大概描述下开发流程和执行流程，这样也可以帮助其他人更快上手，授人以鱼不如授人以渔，多谢了

感谢您的建议，我这边文档更新会通知你的
