### ISSUE TITLE
大佬好，dataintegration.sql数据库脚本不全运行不起来

### ISSUE THREAD

**Issue by lanpiao** [young-datafan-ooooo1/data-integration#88]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by EchoXiaoLang** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

你用的数据库版本是

**Comment by lanpiao** [comment]
5.7

**Comment by lanpiao** [comment]
![image](https://user-images.githubusercontent.com/11692327/170664381-0d6f83ca-c7cb-4dd0-ba83-f745610035ba.png)

**Comment by lanpiao** [comment]
打开dataintegration.sql文件就可以看到脚本不全，就只新建了一个表，执行到后面就报错了

**Comment by EchoXiaoLang** [comment]
> ![image](https://user-images.githubusercontent.com/11692327/170664381-0d6f83ca-c7cb-4dd0-ba83-f745610035ba.png)

你可以尝试通过dump 命令导入或者使用工具导入选择sql文件。这个sql其他拉取代码的人员是可以导入成功的
