### ISSUE TITLE
各位大佬有没有个QQ交流群啊？

### ISSUE THREAD

**Issue by gz518518** [young-datafan-ooooo1/data-integration#89]
我现在本地代码已经部署完了，但是还是报错，咱们有没有一个本地部署测试的说明，能不能麻烦发一下，谢谢了

**Comment by EchoXiaoLang** [comment]
![image](https://user-images.githubusercontent.com/25915539/198979963-16f2fbdc-7c5a-4d0d-8804-e8b269bb4610.png)






微信群-11月7日前 有效

**Comment by oday-xiexin** [comment]
> ![image](https://user-images.githubusercontent.com/25915539/178697670-ba4b88d6-f940-45e7-8078-10dc2a9619b0.png)
> 
> 微信群-7月20日前 有效

过期了

**Comment by aolingxiao** [comment]
已过期，能再发一个吗

**Comment by zklymm** [comment]
过期了，能否提供新的二维码

**Comment by skycsdn** [comment]
过期了，能否提供新的二维码

**Comment by zhoufeng4350170** [comment]
能再发个二维码吗
