### ISSUE TITLE
请问前端依赖安装失败怎么解决？

### ISSUE THREAD

**Issue by easy868** [young-datafan-ooooo1/data-integration#92]
![image](https://user-images.githubusercontent.com/22834466/171142908-3429f3e9-94ad-4d00-ade0-1c1980a80a5c.png)

**Comment by easy868** [comment]
node:16.8.0
npm:7.21.0

**Comment by liujunleo** [comment]
@easy868 你好，可以检查下npm源

**Comment by cly-123** [comment]
我也这样，你这个问题解决了吗
