### ISSUE TITLE
无法登录，报Token错误

### ISSUE THREAD

**Issue by lmj12345sx** [young-datafan-ooooo1/data-integration#96]
部署过程中没有报错，部署完成后，访问UI登录页面，按照官网说明输入默认的用户名和密码登录不上去！ 默认的用户是admin，默认的密码是Prime@2020。很急！我们想全面了解一下这个产品，希望看到后尽快回复，谢谢

**Comment by EchoXiaoLang** [comment]
@lmj12345sx 可以把发下你的dataintegration-gateway 的日志，和sso服务的日志看下

**Comment by lmj12345sx** [comment]
您发送到刘梦杰的邮件已接收！阅读后会尽快给您回复！

**Comment by lmj12345sx** [comment]
你好，日志是在docker里吗？我没找到对应的日志文件，能否加个微信或者留个电话，咱们沟通一下？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "young-datafan/data-integration"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月9日(星期四) 晚上7:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [young-datafan/data-integration] 无法登录，报Token错误 (Issue #96)





 
@lmj12345sx 可以把发下你的dataintegration-gateway 的日志，和sso服务的日志看下

**Comment by EchoXiaoLang** [comment]
@lmj12345sx   看你是怎么部署的  是本地idea还是docker 了， https://github.com/young-datafan/data-integration/issues/89 这有个群，你可以去群里讨论

**Comment by lmj12345sx** [comment]
是按照github项目给出的文档部署的，按照docker方式部署的。
发的群链接我点不进去。。。
排查了一遍，看这个sso的docker服务好像一直没起来，附件有截图，帮忙看一下。谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "young-datafan/data-integration"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月10日(星期五) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [young-datafan/data-integration] 无法登录，报Token错误 (Issue #96)





 
@lmj12345sx   看你是怎么部署的  是本地idea还是docker 了， #89 这有个群，你可以去群里讨论

**Comment by EchoXiaoLang** [comment]
@lmj12345sx 没收到你的附件，截图这里也可以发,直接复制粘贴进来就行了

**Comment by lmj12345sx** [comment]
您发送到刘梦杰的邮件已接收！阅读后会尽快给您回复！
