### ISSUE TITLE
请问节点之间是怎么连接的

### ISSUE THREAD

**Issue by 702683646** [young-datafan-ooooo1/data-integration#99]
![111](https://user-images.githubusercontent.com/54172545/174518583-764edd42-68b1-491d-b7cb-760db7b5ed77.png)

**Comment by 702683646** [comment]
想进一下交流群，谢谢大佬

**Comment by EchoXiaoLang** [comment]
@702683646 可以通过按住shift ，然后选中控件，按住鼠标左键移动，会有一根连接线，群已经更新https://github.com/young-datafan/data-integration/issues/89
